pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/docker
      - ./public/assets
      - /usr/local/bundle
    volumes:
      - /tmp/cache:/cache

  test_secrets:
    image: golang
    secrets: 
      - source: access_key
        target: aws_access_key_id
      - source: secret_key
        target: aws_secret_access_key
    commands: 
      - echo $AWS_ACCESS_KEY_ID

  ecr:
    image: plugins/ecr
    repo: shopping
    registry: 581987047035.dkr.ecr.ap-southeast-2.amazonaws.com
    tags: ${DRONE_COMMIT_SHA:0:8}
    region: ap-southeast-2
    storage_path: /drone/docker
    secrets: 
      - source: access_key
        target: aws_access_key_id
      - source: secret_key
        target: aws_secret_access_key

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/docker
      - ./public/assets
      - /usr/local/bundle
    # Mount the cache volume, needs "Trusted"
    volumes:
      - /tmp/cache:/cache
