pipeline:
  build:
    image: docker
    commands:
      - docker --tls=false ps

# services:
#   docker:
#     image: docker:dind
#     command: [ "--storage-driver=vfs", "--tls=false" ]
#     privileged: true
