pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/docker
    volumes:
      - /tmp/cache:/cache
  ecr:
    image: plugins/ecr
    access_key: AKIAJZJLGZ4DN6SE4GVA
    secret_key: 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
    repo: shopping
    registry: 581987047035.dkr.ecr.ap-southeast-2.amazonaws.com
    tags: ${DRONE_COMMIT_SHA:0:8}
    region: ap-southeast-2
    storage_path: /drone/docker

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/docker
    # Mount the cache volume, needs "Trusted"
    volumes:
      - /tmp/cache:/cache
