pipeline:
  build:
    image: docker
    # environment:
      # - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker --tls=false ps

# services:
#   docker:
#     image: docker:dind
#     command: [ "--storage-driver=vfs", "--tls=false" ]
#     # privileged: true
