pipeline:
  build:
    image: ruby
    # environment:
    #   - DOCKER_HOST=tcp://docker:2375
    commands:
      - echo "Hello"

# services:
#   docker:
#     image: docker:dind
#     command: [ "--storage-driver=vfs", "--tls=false" ]
#     # privileged: true
